server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demoProject
    username: postgres
    password: 301811
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formatsql: true